[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ksl-docs"
authors = [{name = "Mohsin Ahmed Shaikh", email = "mohsin.shaikh@kaust.edu.sa"}]
dynamic = ["version", "description"]
